//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeftyApp2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentTracking
    {
        public int DocumentTrackingID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UniqueID { get; set; }
        public int BPID { get; set; }
        public string TPName { get; set; }
        public string TransactionSetID { get; set; }
        public string Direction { get; set; }
        public string OriginalFileName { get; set; }
        public string ProcessingStatus { get; set; }
        public string ArchiveFileName { get; set; }
        public string ArchiveFilePath { get; set; }
        public string OverallStatus { get; set; }
        public string FileDate { get; set; }
        public string Checksum { get; set; }
        public string ISAControlNum { get; set; }
        public string GSControlNum { get; set; }
        public Nullable<int> STCount { get; set; }
        public string ISAFANum { get; set; }
        public string GSFANum { get; set; }
        public Nullable<int> FACount { get; set; }
        public string FALink { get; set; }
        public string Mailbox { get; set; }
        public Nullable<int> MailboxMessageID { get; set; }
    }
}
